DROP TABLE IF EXISTS channels CASCADE;
CREATE TABLE channels (
  id SERIAL PRIMARY KEY NOT NULL,
  room_id INTEGER REFERENCES rooms(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) DEFAULT 'text'
);